### ISSUE TITLE
Flexibility 2.0.1 issues with IE9

### ISSUE THREAD

**Issue by gneatgeek** [jonathantneal/flexibility#72]
Good morning,

I've been seeing a few issues with IE9 and the latest version of Flexiblity (1.0.6 works as expected).  I noticed that there are other issues that may be related, but do not seem to be the same as what I'm seeing so I figured it'd be easier for you if I logged a new issue.

Basically, I have two simple flexbox components next to each other.  Upon running `flexibility(document.body);`, the layout blows up.

__Before Flexibility:__
![screen shot 2016-07-19 at 9 03 51 am](https://cloud.githubusercontent.com/assets/1232730/16953261/ff009382-4d91-11e6-8fd5-13f24c6c4cd4.png)

__After Flexibility:__
![screen shot 2016-07-19 at 9 04 22 am](https://cloud.githubusercontent.com/assets/1232730/16953264/029c6ec6-4d92-11e6-9eae-3261b6de26aa.png)

Here is a jsbin with all of the code for easy IE9 testing: http://jsbin.com/lesaxanune/edit?html,css,output

Since I'm not sure how long this jsbin will stay alive, here is the code below:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flexibility/2.0.1/flexibility.js"></script>

</head>
<body>
<p>The solid red border shows the container element, not the bar component</p>

<div id="horizontal">
  <div class="Bar Bar--horizontal">
    <div class="Bar-start Bar--medium">Start</div>
    <div class="Bar-middle">Middle</div>
    <div class="Bar-end Bar--medium">End</div>
  </div>
</div>

<div id="vertical">
  <div class="Bar Bar--vertical">
    <div class="Bar-start Bar--medium">Start</div>
    <div class="Bar-middle">Middle</div>
    <div class="Bar-end Bar--medium">End</div>
  </div>
</div>
    
</body>
</html>
```

```css
.Bar {
  box-sizing: border-box;
  -js-display: flex;
  display: flex;
  justify-content: space-between;
}

.Bar--horizontal {
  align-items: center;
  flex-wrap: nowrap;
  border: 1px dashed blue;
  padding: 0.5rem;
  height: 100%;
}

.Bar--vertical {
  flex-wrap: nowrap;
  flex-direction: column;
  border: 1px dashed blue;
  padding: 0.5rem;
  height: 100%;
}

.Bar-start {
  order: 0;
  border: 1px dashed #ccc;
}

.Bar-middle {
  order: 1;
  border: 1px dashed #ccc;
}

.Bar-end {
  order: 2;
  border: 1px dashed #f00;
}

.Bar--horizontal .Bar-start {
  text-align: left;
}

.Bar--horizontal .Bar-middle {
  text-align: center;
}

.Bar--horizontal .Bar-end {
  text-align: right;
}

.Bar--horizontal .Bar--medium {
  min-width: 30%;
}

.Bar--vertical .Bar--medium {
  min-height: 30%;
}

#horizontal {
  border: 1px solid red;
  width: 75%;
  height: 100px;
  margin-bottom: 10px;
}

#vertical {
  border: 1px solid red;
  width: 15%;
  height: 500px;
  margin-bottom: 10px;
}
```
